Mensagens:
  Sem-Permissao: "&c&lERRO! &7- &cSem permissão."
  Modo-Ativado: "&a&lSUCESSO! &7- &aModo ativado."
  Modo-Desativado: "&a&lSUCESSO! &7- &aModo desativado."
  Localizacao-Setada: "&a&lSUCESSO! &7- &aLocalização setada."
  Not-A-Player: "&c&lERRO! &7- &cIsso não é um player." # "Não é um player"
  Puxado-Para-A-Jail: "&c&ldvAdmin &7- &cVocê foi puxado para a jail, digite seu discord no chat imediatamente."
  Player-Puxado: "&a&lSUCESSO! &7- &aPlayer puxado para a jail."
  Troca-Realizada: "&a&lSUCESSO! &7- &aTroca realizada."
  Inventario-Aberto: "&a&lSUCESSO! &7- &aDano aplicado e inventario de &f{player} &aaberto."
  No-Fall-Testado: "&a&lSUCESSO! &7- &aNo-Fall testado."
  Build-Ativada: "&a&lSUCESSO! &7- &aBuild ativada."
  Build-Desativada: "&a&lSUCESSO! &7- &aBuild desativada."
  Ative-A-Build: "&c&lERRO! &7- &cUse &f/build &cpara ativar a build."
  Impossivel-Dropar: "&c&lERRO! &7- &cVocê não pode dropar um item no modo admin."